### ISSUE TITLE
[FEATURE] Adding Contact/Reach Me Section

### ISSUE THREAD

**Issue by at-the-vr** [Anisha7860/Fun_igniter#17]
Hi Anisha, I wondered if your application can have some Social Links to your GitHub/other Social Media along side for additional reach
> Do I want to work on this Feature ? Yeah

**Comment by Anisha7860** [comment]
aye , go ahead , add them

**Comment by at-the-vr** [comment]
Hey Anisha, seems this Issue was already fixed by other folks, I will unassign myself and check something else to explore around 😄

**Comment by Anisha7860** [comment]
Yes shure
