### ISSUE TITLE
[Feature] Adding change theme color button

### ISSUE THREAD

**Issue by pandeatul27** [Anisha7860/Fun_igniter#18]
Option to change theme color button(from green to red) just like dark mode/light mode button

**Comment by pandeatul27** [comment]
@Anisha7860 Can I work on this issue under hacktoberfest?

**Comment by Anisha7860** [comment]
Yep , do tht

**Comment by vinay-pseudo** [comment]
Can I be assigned to this, it's been open for 2 days now
