### ISSUE TITLE
[FEATURE]Add Comment /Feedback Section for increasing interactivity

### ISSUE THREAD

**Issue by AryanSahoo-2003** [Anisha7860/Fun_igniter#28]
Hola @Anisha7860 , I was thinking if a comment section could be added in your application so as to get some fun feedback as well as to encourage other people to engage in it by seeing other people's comment or commenting on other people's comment by nesting comment.
Can you assign it to me?

**Comment by AryanSahoo-2003** [comment]
Ma'am is it okay if I just add comment box and stuff without storing data as I have only learnt about front-end dev and a bit about MySQL...?

**Comment by Anisha7860** [comment]
Yes do tht

**Comment by AryanSahoo-2003** [comment]
actually ma'am I learned php when I commented this(6 hours) as I was eager to learn and have not learnt it..I now have practically done 80% of comment section but I have done it in my local machine and added a text file to save the comments ...is it okay or should I first learn how to use online database to store the old comments?

**Comment by Anisha7860** [comment]
Yes, you can do that. And thn when you finish it, you can add tht too..

**Comment by AryanSahoo-2003** [comment]
![After my commit](https://user-images.githubusercontent.com/110082824/193991160-a9ce4a33-5d77-4f21-987e-bc74028068e9.jpg)
This is the interface I made..is it okay Ma'am?

**Comment by AryanSahoo-2003** [comment]
I have edited your index.html to index.php and made changes there only in my forked repo

**Comment by Anisha7860** [comment]
Are no no , don't make it like tht

**Comment by Anisha7860** [comment]
Don't change the html to php

**Comment by AryanSahoo-2003** [comment]
ok i am just adding a comment box and stuff as .htaccess file is not working in my local system

**Comment by AryanSahoo-2003** [comment]
i have done pull request ma'am..please check it

**Comment by AryanSahoo-2003** [comment]
Hello ma'am..I have resolved the conflicts,can you check it again?

**Comment by AryanSahoo-2003** [comment]
Hey ,,,why this repo got excluded
