### ISSUE TITLE
[Feature] Add footer for better user interaction

### ISSUE THREAD

**Issue by heyaadarsh** [Anisha7860/Fun_igniter#34]
Hi @Anisha7860 
I visited the website, the techy UI is really impressive, but I saw that footer section is missing here. I think if we add a footer section it will enhance the UI. I can add a relevant footer with social icons, matching to the current design. I am very curious to do that! 
May you please assign it to me?

**Comment by Anisha7860** [comment]
Yeah shure

**Comment by heyaadarsh** [comment]
> Yeah shure

Thank you so much for assigning this task to me. I have started working on it.

**Comment by Anisha7860** [comment]
Okay
